---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new, new features, features, release notes, enhancements 
summary: Cloud Volumes ONTAP 9.12.0 包含新的增強功能。 
---
= Cloud Volumes ONTAP 9.12.0 的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.12.0 包含新的增強功能。

最新版的BlueXP也會提供其他功能和增強功能。如 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["BlueXP版本說明"^]需詳細資訊、請參閱。



== 9.12.0 P1 （ 2022 年 12 月 15 日）

Cloud Volumes ONTAP 9.12.0 P1 現已在 AWS 和 Google Cloud 中推出。此版本包含下列新功能。



=== 支援AWS中的m6id.32xlarge

Cloud Volumes ONTAP 現在支援 AWS 中的 m6id.32xlarge EC2 執行個體類型。

如需詳細資訊、請前往link:reference-configs-aws.html["支援的組態頁面"]。



== 升級附註

請閱讀這些附註、深入瞭解升級至此版本的相關資訊。



=== 如何升級

必須從BlueXP完成升級。Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["瞭解如何在BlueXP通知您時進行升級"^]。



=== 支援的升級途徑

您可以從 9.11.1 版本升級至 Cloud Volumes ONTAP 9.12.0 。BlueXP會提示您將合格Cloud Volumes ONTAP 的更新版升級至此版本。



=== 所需版本的Connector

BlueXP  Connector 必須執行 3.9.24 版或更新版本、才能部署新的 Cloud Volumes ONTAP 9.12.0 系統、並將現有系統升級至此版本。


TIP: 連接器的自動升級預設為啟用、因此您應該執行最新版本。



=== 停機

* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。




=== 使用 C4 、 M4 和 R4 EC2 執行個體類型在 AWS 中升級

在 AWS 中、新的 Cloud Volumes ONTAP 部署不再支援 C4 、 M4 和 R4 EC2 執行個體類型。如果現有的系統執行於c4、m4或r4執行個體類型、則必須變更為c5、m5或R5執行個體系列中的執行個體類型。如果您無法變更執行個體類型、則必須在升級之前啟用增強的網路功能。

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["瞭解如何使用 C4 、 M4 和 R4 EC2 執行個體類型升級 AWS"^]。link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["瞭解如何變更EC2執行個體類型Cloud Volumes ONTAP 以供使用"^]。

請參閱link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp支援"^]以深入瞭解這些執行個體類型的終止可用度和支援。
